### ISSUE TITLE
Do some repo improvements

### ISSUE THREAD

**Issue by Knoxo** [FireHead90544/shortyy#1]
- GitHub now has a new option for repositories called **Discussions**, better turn that on :) [Learn More](https://docs.github.com/en/discussions/quickstart) 
- Create a branch called `gh-pages` and take your site there, rather than keeping it in the `main`

**Comment by FireHead90544** [comment]
- Thanks for the suggestion. I'll turn on the discussions :)
- But as of `gh-pages`, i know what it does, also as it is not hosted on github, just source code is there its deployed on aws so there is no point of using github pages. main branch is default branch though I may merge pull requests in other branches that needs review or something like that :)

**Comment by Knoxo** [comment]
Oh, I thought the website is hosted in GitHub Pages...
Okay then

**Comment by FireHead90544** [comment]
No Problem :)
Thanks for the suggestions BTW.
